# Generated by Django 5.1.3 on 2024-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Full Time'), (2, 'Part Time'), (3, 'Contract'), (5, 'Internship'), (5, 'Temporary')], default=1, max_length=4),
        ),
    ]
